name: Publish to Maven Central

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD || '' }}
        run: |
          # Extract version from tag (removes 'v' prefix if present)
          VERSION=${GITHUB_REF_NAME#v}
          
          # Decode the GPG key from base64 and export it
          export ORG_GRADLE_PROJECT_signingInMemoryKey=$(echo "${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}" | base64 --decode)
          
          # Publish with version override
          ./gradlew publishAllPublicationsToMavenCentralRepository --no-daemon -Pversion=$VERSION